### PR TITLE
Port convert_schema_to_sqlite from rcc.billing

### PR DESCRIPTION
**Pull request by ChemiKyle**
Altered function to accept path to sql file rather than require file be present in package.

The function _could_ also accept a raw sql string, I resisted my temptation to follow this rabbit and left a note for future improvement instead.  
If we're being really nice to the community, we could check for presence of a `perl` binary at the start of the function as well.

This is a precursor to work related to `redcap_summary_metrics`.

---
Note that sqlite has some peculiarities, the most pertinent being that while it _does_ support auto-incrementing primary keys, lines like:

```sql
  `id` bigint NOT NULL AUTO_INCREMENT,
```

need to be expressed as:
```sql
  `id` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
```

for our perl script to translate them. See paragraphs 1 and 2 of [this SO answer](https://stackoverflow.com/a/7906029/7418735).

### CODE REVIEW

**Comment by ChemiKyle** [comment]
I also ported `mutate_columns_to_posixct` from `rcc.billing` in commit [6fe8296](https://github.com/ctsit/redcapcustodian/pull/94/commits/6fe82965d26291a5b5fdcf46404d3448342d6bbe). This is to aid writing automated tests involving in-memory dbs.

**Review by pbchase — APPROVED** [review]
I like what you wrote.  I added a test of `convert_schema_to_sqlite`.

**Comment by pbchase** [comment]
> I like what you wrote. I added a test of `convert_schema_to_sqlite`.

If you like the test I wrote, please merge it. The merging ball is in _your_ court

**Comment by ChemiKyle** [comment]
Probably not needed, but I threw away the in-memory SQLite table at the end of the `convert_schema_to_sqlite` test since it feels proper.

**Pull request merged**
